# 默认训练器配置
trainer:
  max_epochs: 10
  accelerator: auto
  devices: auto
  precision: 32
  log_every_n_steps: 50
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  enable_progress_bar: true
  enable_model_summary: true