import { unstable_v2_createSession, tool } from '@anthropic-ai/claude-agent-sdk'
import { z } from 'zod'
import { JiraClient } from '../lib/jira'
import { readJiraConfig } from '../lib/config'
import { applyActions } from '../lib/tools/jiraActions'
import { buildExecutionPlan } from '../lib/executionPlan'
import { readArgValue, hasFlag } from '../lib/utils'
import { runExecutionPlan, verifyMultiAgentExecution } from '../lib/agentRunner'

const config = readJiraConfig()
const jira = new JiraClient(config)

const jiraTools = [
  tool(
    'get_execution_plan',
    'Get the current sprint execution plan based on user input',
    { userInput: z.string(), sprintName: z.string().optional() },
    async ({ userInput, sprintName }: { userInput: string; sprintName?: string }) => {
      const plan = await buildExecutionPlan(
        jira,
        {
          userInput,
          sprintName,
          closeWhenDone: false
        },
        { projectKey: config.projectKey, boardId: config.boardId }
      )
      return plan
    }
  ),
  tool(
    'apply_jira_actions',
    'Apply JIRA actions (comments/transitions) generated by sub-agents',
    {
      actions: z.array(
        z.object({
          type: z.enum(['comment', 'transition']),
          issueKey: z.string(),
          text: z.string().optional(),
          to: z.string().optional()
        })
      ),
      allowedIssueKeys: z.array(z.string()).optional()
    },
    async ({
      actions,
      allowedIssueKeys
    }: {
      actions: Array<{ type: 'comment' | 'transition'; issueKey: string; text?: string; to?: string }>
      allowedIssueKeys?: string[]
    }) => {
      const applied = await applyActions(jira, actions, allowedIssueKeys ? new Set(allowedIssueKeys) : undefined)
      return { applied_count: applied, status: 'success' }
    }
  )
]

async function main() {
  const userInput = readArgValue(process.argv, '--input') || 'Check current sprint status'
  const sprintName = readArgValue(process.argv, '--sprint-name')
  const useProgrammatic = !hasFlag(process.argv, '--llm-orchestrated')

  if (useProgrammatic) {
    const plan = await buildExecutionPlan(
      jira,
      { userInput, sprintName, closeWhenDone: false },
      { projectKey: config.projectKey, boardId: config.boardId }
    )
    const summary = await runExecutionPlan({
      jira,
      plan,
      parallel: true,
      model: process.env.ANTHROPIC_MODEL ?? process.env.LLM_MODEL ?? 'deepseek-chat'
    })
    const verify = await verifyMultiAgentExecution({ summary })
    console.log('[Runner] Dev invoked:', summary.devInvoked)
    console.log('[Runner] QA invoked:', summary.qaInvoked)
    console.log('[Runner] Scrum invoked:', summary.scrumInvoked)
    console.log('[Runner] JIRA actions applied:', summary.totalActionsApplied)
    console.log('[Runner] Verify:', verify.ok ? 'ok' : `failed: ${verify.message}`)
    return
  }

  await using session = unstable_v2_createSession({
    model: process.env.ANTHROPIC_MODEL ?? process.env.LLM_MODEL ?? 'deepseek-chat',
    tools: jiraTools
  })

  await session.send({
    type: 'user',
    message: {
      role: 'user',
      content: `你是一个 Sprint Orchestrator。请执行以下步骤：\n1. 调用 get_execution_plan 获取当前 Sprint 的执行计划。\n2. 分析计划中的 tasks，识别出需要 Scrum Master, DevTeam, Quality 处理的任务。\n3. 按顺序调度子智能体（scrum-master-agent, development-team-agent, quality-agent）来执行这些任务。\n   - 注意：你可以并行调度 DevTeam 和 Quality 任务，但要确保逻辑依赖。\n   - 每个子智能体执行完后，如果产生了 actions，请调用 apply_jira_actions 工具应用变更。\n4. 最后生成一份简要的执行报告。\n\n用户输入: ${userInput}`
    }
  })

  for await (const msg of (await session).receive()) {
    if (msg.type === 'assistant') {
      const text = msg.message.content
        .filter((b: any) => b.type === 'text')
        .map((b: any) => b.text)
        .join('')
      if (text) console.log(`[Claude]: ${text}`)
    } else if (msg.type === 'error') {
      console.error('[Error]:', msg.error)
    }
  }
}

main().catch(console.error)
