version: '3.8'

services:
  cnn-cpu:
    build:
      context: ../..
      dockerfile: deploy/cpu/Dockerfile
    container_name: cnn-tutorial-cpu
    ports:
      - "8888:8888"  # Jupyter Lab
      - "8000:8000"  # FastAPI/其他服务
    volumes:
      - ../..:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    healthcheck:
      test: ["CMD", "python", "-c", "import torch; import paddle; print('CPU ML libraries loaded')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  data:
    driver: local

networks:
  default:
    name: cnn-cpu-network